services:
  db:
    image: postgres:16-alpine
    container_name: spring_security_jwt_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data_spring_security_jwt_db:/var/lib/postgresql/data

volumes:
  postgres-data_spring_security_jwt_db: