services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-8.8.1}
    container_name: e_approval_elasticsearch
    restart: always
    ports:
      - '${ELASTIC_PORT:-9200}:9200'
    volumes:
      - ./data/elastic-${ELASTIC_VERSION:-8.8.1}:/usr/share/elasticsearch/data
#      - /etc/letsencrypt/live/integ.allweb.com.kh/privkey.pem:/usr/share/elasticsearch/config/certs/privkey.pem
#      - /etc/letsencrypt/live/integ.allweb.com.kh/fullchain.pem:/usr/share/elasticsearch/config/certs/fullchain.pem
    environment:
      - node.name=elastic
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
#      - xpack.security.http.ssl.key=certs/privkey.pem
#      - xpack.security.http.ssl.certificate=certs/fullchain.pem
#      - xpack.security.http.ssl.certificate_authorities=certs/fullchain.pem
      - xpack.security.transport.ssl.enabled=false
#      - xpack.security.transport.ssl.key=certs/privkey.pem
#      - xpack.security.transport.ssl.certificate=certs/fullchain.pem
#      - xpack.security.transport.ssl.certificate_authorities=certs/fullchain.pem
#      - xpack.security.transport.ssl.verification_mode=certificate
#      - xpack.license.self_generated.type=${LICENSE}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536