#version: '3.5'
#services:
#  keycloak:
#    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
#    container_name: e_approval_keycloak
#    command: start-dev
#    restart: always
#    ports:
#      - '${KEYCLOAK_HTTPS_PORT:-8443}:8443'
#    environment:
#      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
#      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
##      - KC_HEALTH_ENABLED=true
##      - KC_METRICS_ENABLED=true
#      KC_HOSTNAME: ${KEYCLOAK_HOST}
##      KC_PROXY: edge
#      KC_DB: postgres
#      KC_DB_SCHEMA: public
#      KC_DB_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
#      KC_DB_USERNAME: ${POSTGRES_USERNAME}
#      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
#      KC_FEATURES: token-exchange,admin-fine-grained-authz
##      - KC_HTTPS_CERTIFICATE_FILE=/etc/x509/https/tls.crt
##      - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/x509/https/tls.key

version: '3.8'
services:
  database:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - local

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    command: start-dev
    restart: always
    ports:
      - "9082:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin@1234
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://database:5433/keycloak
      KC_HOSTNAME: localhost
      KC_FEATURES: token-exchange,admin-fine-grained-authz
    networks:
      - local

networks:
  local:
